steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '14'  # ou a versão que você está usando

  - name: Install dependencies
    run: npm install

  - name: Install Firebase CLI
    run: npm install -g firebase-tools

  - name: Authenticate with Firebase
    run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

  - name: Deploy to Firebase
    run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

